/**
 * AI-132: freshness tests for generated modules.
 *
 * Verifies that committed generated modules match what the generation scripts produce.
 * If this test fails, run the corresponding script to regenerate.
 */
import { describe, expect, it } from 'vitest';
import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(__dirname, '..', '..');

describe('AI-132: generated module freshness', () => {
  it('swagger-spec.ts matches freshly generated spec (run: npx tsx scripts/generate-swagger-spec.ts)', () => {
    // Generate fresh spec to a temp location by running the script
    const freshOutput = execSync('npx tsx scripts/generate-swagger-spec.ts', {
      cwd: ROOT,
      encoding: 'utf-8',
      timeout: 30000,
    });

    // Read the freshly generated file
    const freshPath = join(ROOT, 'server', 'data', 'swagger-spec.ts');
    const fresh = readFileSync(freshPath, 'utf-8');

    // Read the committed file from git
    const committed = execSync('git show HEAD:server/data/swagger-spec.ts', {
      cwd: ROOT,
      encoding: 'utf-8',
      timeout: 10000,
    });

    expect(fresh).toBe(committed);
  });

  it('directus-schema.ts matches snapshot script output (run: DIRECTUS_URL=... DIRECTUS_STATIC_TOKEN=... npx tsx scripts/directus-schema-snapshot.ts)', () => {
    // This test verifies the module wasn't hand-edited.
    // We can't regenerate without Directus access, so we check that the module
    // was generated by the script (has the auto-generated header).
    const schemaPath = join(ROOT, 'server', 'data', 'directus-schema.ts');
    const content = readFileSync(schemaPath, 'utf-8');
    expect(content).toContain('Auto-generated by scripts/directus-schema-snapshot.ts');
    expect(content).toContain('export const DIRECTUS_SCHEMA');
    expect(content).toContain('export interface CollectionSchema');
  });
});
