#!/usr/bin/env npx tsx
/**
 * Fetch Directus field schema and save as TypeScript module.
 *
 * Usage:
 *   DIRECTUS_URL=... DIRECTUS_STATIC_TOKEN=... npx tsx scripts/directus-schema-snapshot.ts
 *
 * Requires DIRECTUS_URL and DIRECTUS_STATIC_TOKEN environment variables.
 * Output: server/data/directus-schema.ts
 */
import axios from 'axios';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface DirectusField {
  collection: string;
  field: string;
}

async function main() {
  const url = process.env.DIRECTUS_URL;
  const token = process.env.DIRECTUS_STATIC_TOKEN;
  if (!url || !token) {
    console.error('DIRECTUS_URL and DIRECTUS_STATIC_TOKEN required');
    process.exit(2);
  }

  const resp = await axios.get(`${url}/fields`, {
    headers: { Authorization: `Bearer ${token}` },
    params: { limit: -1 },
  });

  const fields: DirectusField[] = resp.data.data;
  // Group by collection
  const grouped = new Map<string, string[]>();
  for (const f of fields) {
    const arr = grouped.get(f.collection) || [];
    arr.push(f.field);
    grouped.set(f.collection, arr);
  }

  const snapshot = [...grouped.entries()].map(([collection, fieldNames]) => ({
    collection,
    fields: fieldNames.sort(),
  }));

  // Sort by collection name for stable output
  snapshot.sort((a, b) => a.collection.localeCompare(b.collection));

  // Generate TypeScript module
  const lines: string[] = [
    '// Auto-generated by scripts/directus-schema-snapshot.ts',
    '// Do not edit manually. Run the script to update.',
    'export interface CollectionSchema {',
    '  collection: string;',
    '  fields: string[];',
    '}',
    '',
    'export const DIRECTUS_SCHEMA: CollectionSchema[] = [',
  ];
  for (const c of snapshot) {
    const fieldsStr = c.fields.map((f) => `'${f}'`).join(', ');
    lines.push(`  { collection: '${c.collection}', fields: [${fieldsStr}] },`);
  }
  lines.push('];');

  const outPath = join(__dirname, '..', 'server', 'data', 'directus-schema.ts');
  writeFileSync(outPath, lines.join('\n') + '\n');
  console.log(`Schema snapshot saved: ${outPath} (${snapshot.length} collections)`);
}

main().catch((err) => {
  console.error('Failed to fetch schema:', err.message);
  process.exit(1);
});
