#!/usr/bin/env npx tsx
/**
 * Generate swagger spec from JSDoc annotations and save as TypeScript module.
 *
 * Run during build, before esbuild bundles the server.
 * Output: server/data/swagger-spec.ts
 *
 * Usage: npx tsx scripts/generate-swagger-spec.ts
 */
import swaggerJSDoc from 'swagger-jsdoc';
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// No servers list on purpose. With it absent, Swagger UI addresses the origin the
// document was served from, which is right in every environment; baking an origin in
// would make the generated module depend on the machine that generated it.
const options: swaggerJSDoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'SMM Manager API',
      version: '1.0.0',
      description: 'AI-powered Social Media Content Management Platform API.',
      contact: { name: 'SMM Manager Support', email: 'support@nplanner.ru' },
      license: { name: 'Proprietary', url: '/terms' },
    },
    // servers: [] — populated at runtime from environment
  },
  apis: [
    './server/swagger-endpoints.ts',
    './server/routes.ts',
    './server/api/*.ts',
    './server/routes/*.ts',
  ],
};

const specs = swaggerJSDoc(options);
const json = JSON.stringify(specs, null, 2);

const lines = [
  '// Auto-generated by scripts/generate-swagger-spec.ts',
  '// Do not edit manually. Run the script to update.',
  '// To verify freshness: npx vitest run server/__tests__/ai132-generated-freshness.test.ts',
  '',
  '// eslint-disable-next-line @typescript-eslint/no-explicit-any',
  'export const SWAGGER_SPEC: Record<string, any> = ' + json + ';',
];

const outPath = join(__dirname, '..', 'server', 'data', 'swagger-spec.ts');
writeFileSync(outPath, lines.join('\n') + '\n');

// Count paths
const pathCount = specs.paths ? Object.keys(specs.paths).length : 0;
const methodCount = specs.paths
  ? Object.values(specs.paths).reduce((sum: number, p: any) => sum + Object.keys(p).length, 0)
  : 0;
console.log(`Swagger spec saved: ${outPath} (${pathCount} paths, ${methodCount} methods)`);
