export interface ReportTranslations {
  branding: {
    productName: string;
  };
  cover: {
    title: string;
    campaign: string;
    period: string;
    generatedAt: string;
  };
  common: {
    untitled: string;
    notAvailable: string;
    anonymous: string;
  };
  overview: {
    title: string;
    totalPosts: string;
    totalViews: string;
    totalLikes: string;
    totalReposts: string;
    totalComments: string;
    avgEngagement: string;
  };
  engagement: {
    title: string;
    views: string;
    likes: string;
    reposts: string;
    comments: string;
  };
  topPosts: {
    title: string;
    post: string;
    platform: string;
    views: string;
    likes: string;
    engagement: string;
  };
  sentiment: {
    title: string;
    positive: string;
    neutral: string;
    negative: string;
    totalComments: string;
  };
  platforms: {
    title: string;
    platform: string;
    posts: string;
    views: string;
    engagement: string;
  };
  footer: {
    page: string;
    generatedBy: string;
  };
  excel: {
    overview: string;
    posts: string;
    comments: string;
    platforms: string;
    title: string;
    content: string;
    scheduledFor: string;
    publishedAt: string;
    status: string;
    comment: string;
    sentimentScore: string;
  };
}

export const translations: Record<string, ReportTranslations> = {
  ru: {
    branding: {
      productName: 'SMM Manager'
    },
    cover: {
      title: 'Отчет по кампании',
      campaign: 'Кампания',
      period: 'Период',
      generatedAt: 'Создано'
    },
    common: {
      untitled: 'Без названия',
      notAvailable: 'Н/Д',
      anonymous: 'Аноним'
    },
    overview: {
      title: 'Общая статистика',
      totalPosts: 'Всего постов',
      totalViews: 'Просмотры',
      totalLikes: 'Лайки',
      totalReposts: 'Репосты',
      totalComments: 'Комментарии',
      avgEngagement: 'Средняя вовлеченность'
    },
    engagement: {
      title: 'Динамика вовлеченности',
      views: 'Просмотры',
      likes: 'Лайки',
      reposts: 'Репосты',
      comments: 'Комментарии'
    },
    topPosts: {
      title: 'Топ-5 постов по вовлеченности',
      post: 'Пост',
      platform: 'Платформа',
      views: 'Просмотры',
      likes: 'Лайки',
      engagement: 'Вовлеченность'
    },
    sentiment: {
      title: 'Анализ комментариев',
      positive: 'Позитивные',
      neutral: 'Нейтральные',
      negative: 'Негативные',
      totalComments: 'Всего комментариев'
    },
    platforms: {
      title: 'Статистика по платформам',
      platform: 'Платформа',
      posts: 'Посты',
      views: 'Просмотры',
      engagement: 'Вовлеченность'
    },
    footer: {
      page: 'Страница',
      generatedBy: 'Создано в SMM Manager'
    },
    excel: {
      overview: 'Общая статистика',
      posts: 'Посты',
      comments: 'Комментарии',
      platforms: 'Платформы',
      title: 'Название',
      content: 'Контент',
      scheduledFor: 'Дата публикации',
      publishedAt: 'Опубликовано',
      status: 'Статус',
      comment: 'Комментарий',
      sentimentScore: 'Оценка'
    }
  },
  en: {
    branding: {
      productName: 'SMM Manager'
    },
    cover: {
      title: 'Campaign Report',
      campaign: 'Campaign',
      period: 'Period',
      generatedAt: 'Generated at'
    },
    common: {
      untitled: 'Untitled',
      notAvailable: 'N/A',
      anonymous: 'Anonymous'
    },
    overview: {
      title: 'Overview Statistics',
      totalPosts: 'Total Posts',
      totalViews: 'Views',
      totalLikes: 'Likes',
      totalReposts: 'Reposts',
      totalComments: 'Comments',
      avgEngagement: 'Average Engagement'
    },
    engagement: {
      title: 'Engagement Dynamics',
      views: 'Views',
      likes: 'Likes',
      reposts: 'Reposts',
      comments: 'Comments'
    },
    topPosts: {
      title: 'Top 5 Posts by Engagement',
      post: 'Post',
      platform: 'Platform',
      views: 'Views',
      likes: 'Likes',
      engagement: 'Engagement'
    },
    sentiment: {
      title: 'Comment Analysis',
      positive: 'Positive',
      neutral: 'Neutral',
      negative: 'Negative',
      totalComments: 'Total Comments'
    },
    platforms: {
      title: 'Platform Statistics',
      platform: 'Platform',
      posts: 'Posts',
      views: 'Views',
      engagement: 'Engagement'
    },
    footer: {
      page: 'Page',
      generatedBy: 'Generated by SMM Manager'
    },
    excel: {
      overview: 'Overview',
      posts: 'Posts',
      comments: 'Comments',
      platforms: 'Platforms',
      title: 'Title',
      content: 'Content',
      scheduledFor: 'Scheduled For',
      publishedAt: 'Published At',
      status: 'Status',
      comment: 'Comment',
      sentimentScore: 'Sentiment'
    }
  },
  es: {
    branding: {
      productName: 'SMM Manager'
    },
    cover: {
      title: 'Informe de Campaña',
      campaign: 'Campaña',
      period: 'Período',
      generatedAt: 'Generado el'
    },
    common: {
      untitled: 'Sin título',
      notAvailable: 'N/D',
      anonymous: 'Anónimo'
    },
    overview: {
      title: 'Estadísticas Generales',
      totalPosts: 'Total de Publicaciones',
      totalViews: 'Vistas',
      totalLikes: 'Me gusta',
      totalReposts: 'Compartidos',
      totalComments: 'Comentarios',
      avgEngagement: 'Compromiso Promedio'
    },
    engagement: {
      title: 'Dinámica de Compromiso',
      views: 'Vistas',
      likes: 'Me gusta',
      reposts: 'Compartidos',
      comments: 'Comentarios'
    },
    topPosts: {
      title: 'Top 5 Publicaciones por Compromiso',
      post: 'Publicación',
      platform: 'Plataforma',
      views: 'Vistas',
      likes: 'Me gusta',
      engagement: 'Compromiso'
    },
    sentiment: {
      title: 'Análisis de Comentarios',
      positive: 'Positivos',
      neutral: 'Neutrales',
      negative: 'Negativos',
      totalComments: 'Total de Comentarios'
    },
    platforms: {
      title: 'Estadísticas por Plataforma',
      platform: 'Plataforma',
      posts: 'Publicaciones',
      views: 'Vistas',
      engagement: 'Compromiso'
    },
    footer: {
      page: 'Página',
      generatedBy: 'Generado por SMM Manager'
    },
    excel: {
      overview: 'General',
      posts: 'Publicaciones',
      comments: 'Comentarios',
      platforms: 'Plataformas',
      title: 'Título',
      content: 'Contenido',
      scheduledFor: 'Programado para',
      publishedAt: 'Publicado el',
      status: 'Estado',
      comment: 'Comentario',
      sentimentScore: 'Sentimiento'
    }
  }
};

export function getTranslations(locale: string): ReportTranslations {
  return translations[locale] || translations.ru;
}
